# Generated by Django 4.1.4 on 2022-12-18 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newversion', '0002_alter_data_options_alter_data_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='date_create',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date_create'),
            preserve_default=False,
        ),
    ]
